services:
  ecomDb:
    image: postgres

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    depends_on:
      - ecomDb

volumes:
  postgres_ecomDb:    